# Generated by Django 4.2.6 on 2023-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('female', 'female')], max_length=255)),
            ],
        ),
    ]
