# Generated by Django 4.2.6 on 2023-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
