# Generated by Django 4.2.6 on 2023-10-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reference_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255),
        ),
    ]
