# Generated by Django 4.2.6 on 2023-10-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_reference_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reference',
            new_name='ReferenceData',
        ),
    ]
