# Generated by Django 4.2.6 on 2023-10-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_reference_referencedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255)),
            ],
        ),
    ]
